/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as CollectionsCategoryProductRouteImport } from './routes/collections.$category.$product'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsCategoryProductRoute =
  CollectionsCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => CollectionsCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/collections/$category': typeof CollectionsCategoryRouteWithChildren
  '/collections/$category/$product': typeof CollectionsCategoryProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/collections/$category': typeof CollectionsCategoryRouteWithChildren
  '/collections/$category/$product': typeof CollectionsCategoryProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/collections/$category': typeof CollectionsCategoryRouteWithChildren
  '/collections/$category/$product': typeof CollectionsCategoryProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/collections/$category'
    | '/collections/$category/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/collections/$category'
    | '/collections/$category/$product'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/collections/$category'
    | '/collections/$category/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$category/$product': {
      id: '/collections/$category/$product'
      path: '/$product'
      fullPath: '/collections/$category/$product'
      preLoaderRoute: typeof CollectionsCategoryProductRouteImport
      parentRoute: typeof CollectionsCategoryRoute
    }
  }
}

interface CollectionsCategoryRouteChildren {
  CollectionsCategoryProductRoute: typeof CollectionsCategoryProductRoute
}

const CollectionsCategoryRouteChildren: CollectionsCategoryRouteChildren = {
  CollectionsCategoryProductRoute: CollectionsCategoryProductRoute,
}

const CollectionsCategoryRouteWithChildren =
  CollectionsCategoryRoute._addFileChildren(CollectionsCategoryRouteChildren)

interface CollectionsRouteChildren {
  CollectionsCategoryRoute: typeof CollectionsCategoryRouteWithChildren
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCategoryRoute: CollectionsCategoryRouteWithChildren,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
